[package]
name = "openxr-opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openxr = { version = "0.15", features = ["static"] }
glutin = "0.28"
winapi = "0.3"
glow = "0.11"
glam = "0.20"
